### ISSUE TITLE
Store history in a plain text CSV file

### ISSUE THREAD

**Issue by GreenLunar** [ceyusa/gphone#13]
I see no reason to use an SQLite3 database file for a call history table.

File: `~/.local/share/gphone/history.db`

**Comment by ceyusa** [comment]
Hey @GreenLunar ,

The reason to use sqlite is because it would be easier to generate reports and extract statistics of usage. Try to do that with cvs files is hard. Besides, sqlite is largely used by many project, such as firefox, so it should be a problem to have it already installed.

**Comment by GreenLunar** [comment]
It is not the installation of sqlite3 that bothers me, I like to keep things as simple as possible.

If you made gphone to use and sqlite database for effectuality, then it is fine, I think.

As for the web browser you have mentioned. the people behind it have decided to use a database file in order to remain themselves relevant by making others more dependent on their unreliable and destructive products.
